version: "3.9"
services:
  postgres:
    image: postgres:15.0
    environment:
      POSTGRES_DB: "urldb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./internal/config/init.sql:/docker-entrypoint-initdb.d/10-init.sql
    ports:
      - "5432:5432"
